package com.sample
 
import com.sample.DroolsTest.Caller;
dialect "java"
 
/*rule "check1"
    when
        m : Caller( name:principalName  )
    then
    	System.out.println( "fire by principalName " );
        System.out.println( name );
        m.setSystem(name);       
       // update( m );
end*/

rule "check2"
    when
        m:Caller( userAgent == "abc" )
    then
        System.out.println( "fire by userAgent2" );
    	m.setSystem("frp");       
        //update( m );
        
end

rule "check3"
    when
        m:Caller( userAgent == "tomcat" )
    then
        System.out.println( "fire by userAgent3" );
    	m.setSystem("reb");       
       // update( m );
        
end
